project_id = "fvpunigieavoxgltrtsd"

[functions.create-checkout]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.send-to-printer]
verify_jwt = false

[functions.check-order-status]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = false

[functions.download-pdf]
verify_jwt = false
